// <auto-generated />
using System;
using IgrejaApp.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IgrejaApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250801181655_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("IgrejaApp.Domain.Entities.Batismo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Igreja")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PastorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PastorNomeManual")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PastorId");

                    b.ToTable("Batismos");
                });

            modelBuilder.Entity("IgrejaApp.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BatismoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Celular")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Complemento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConjugeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCasamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Genero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeioAdmissao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naturalidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeConjuge")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMae")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePai")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BatismoId");

                    b.HasIndex("ConjugeId")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("IgrejaApp.Domain.Entities.Batismo", b =>
                {
                    b.HasOne("IgrejaApp.Domain.Entities.Usuario", "Pastor")
                        .WithMany()
                        .HasForeignKey("PastorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pastor");
                });

            modelBuilder.Entity("IgrejaApp.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("IgrejaApp.Domain.Entities.Batismo", "Batismo")
                        .WithMany()
                        .HasForeignKey("BatismoId");

                    b.HasOne("IgrejaApp.Domain.Entities.Usuario", "Conjuge")
                        .WithOne()
                        .HasForeignKey("IgrejaApp.Domain.Entities.Usuario", "ConjugeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Batismo");

                    b.Navigation("Conjuge");
                });
#pragma warning restore 612, 618
        }
    }
}
